# Copy this to the project root directory before running snapcraft

name: bongocat
license: GPL-3.0+
title: BongoCat
summary: A GNU/Linux fork of the bongocat overlay
description: |
      An interactive bongocat fork for GNU/Linux.
version: gnu
grade: devel
confinement: strict
base: core24

apps:
  bongocat:
    command: /bin/bongo
    plugs:
      - x11
      - opengl
      - home
      - joystick
    environment:
      HOME: /home/$USER
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio/
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  meson-deps: # meson is not pre-installed in core24
    plugin: nil
    override-build: |
      apt install meson
  libxdo-pkgconfig-file: # libxdo-dev misses a pkgbuild file
    plugin: nil
    override-build: |
      cp $SNAPCRAFT_PART_SRC/libxdo.pc /usr/lib/pkgconfig/
    source-type: local
    source: ./snap/local
  cxxopts:
    plugin: cmake
    source-type: tar
    source: https://github.com/jarro2783/cxxopts/archive/refs/tags/v3.2.0.tar.gz
  sfml:
    plugin: cmake
    cmake-parameters:
      - -S/root/parts/sfml/src/SFML-3.0.0
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DSFML_BUILD_NETWORK=false
      - -DSFML_BUILD_AUDIO=false
      - -DBUILD_SHARED_LIBS=ON
    source-type: zip
    source: https://www.sfml-dev.org/files/SFML-3.0.0-sources.zip
  bongocat:
    after:
      - sfml
      - cxxopts
      - meson-deps
      - libxdo-pkgconfig-file
    plugin: meson
    meson-parameters:
      - '--buildtype=release'
      - '--prefix=/'
    source-type: local
    source: .
    build-packages:
      - pkg-config
      - ninja-build
      - libgl-dev
      - libudev-dev
      - libxrandr-dev
      - libxcursor-dev
      - libfreetype-dev
      - libxi-dev
      - libxdo-dev
      - libjsoncpp-dev
    stage-packages:
      - libxrandr2
      - libxdo3
      - libjsoncpp25
      - libxcursor1
      - libxi6
  bongocat-data:
    plugin: dump
    source-type: local
    source: .
    stage:
      - img/*
      - share/*
      - snap/local/*
