name: '[CI]: AppImage build'
on:
  workflow_call:

jobs:
  appimage:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: appimagecrafters/appimage-builder:latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build AppImage in docker"
        run: appimage/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bongocat-appimage-x86_64
          path: BongoCat-*-x86_64.AppImage
