name: '[CI]: AppImage build'
on:
  workflow_call:
    inputs:
      upload:
        required: false
        default: false
        type: boolean

jobs:
  appimage:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build AppImage in docker"
        run: docker run --rm -v .:/root -w /root appimagecrafters/appimage-builder:latest appimage/build.sh
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload }}
        with:
          name: bongocat-appimage-x86_64
          path: BongoCat-*-x86_64.AppImage
