name: '[CI]: Archlinux build'
on:
  workflow_call:

jobs:
  makepkg:
    name: "Archlinux build"
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run makepkg in docker"
        run: archlinux/build.sh
