name: '[CI]: Check build'
on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  flatpak:
    name: "Check flatpak build"
    uses: ./.github/workflows/flatpak-build.yml
  appimage:
    name: "Check AppImage build"
    uses: ./.github/workflows/appimage-build.yml
  snap:
    name: "Check Snap build"
    uses: ./.github/workflows/snap-build.yml
  archlinux:
    name: "Check Archlinux build"
    uses: ./.github/workflows/archlinux-build.yml
