name: '[CI]: Check build'
on:
  push:
    branches: 
      - master
      - feature/release

jobs:
  flatpak:
    name: "Check flatpak build"
    uses: ./.github/workflows/flatpak-build.yml
    with:
      upload: false