name: '[CI]: Flatpak build'
on:
  workflow_call:
    inputs:
      upload:
        required: false
        default: false
        type: boolean

jobs:
  flatpak:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - name: "Build package in docker"
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: bongocat.flatpak
        build-bundle: ${{ inputs.upload }}
        manifest-path: flatpak/org.linuxdasein.BongoCat.yml
        cache-key: flatpak-builder-${{ github.sha }}
