name: '[CD]: Publish release'

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_flatpak:
    uses: ./.github/workflows/flatpak-build.yml
    with:
      upload: true
  build_appimage:
    uses: ./.github/workflows/appimage-build.yml
  build_snap:
    uses: ./.github/workflows/snap-build.yml
  release:
    needs: [build_flatpak, build_appimage, build_snap]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: download
        name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: 'Display downloaded artifacts'
        run: ls -R ${{ steps.download.outputs.download-path }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.download.outputs.download-path }}/*
