name: '[CD]: Publish release'
on:
  push:
    branches: 
      - master
      - feature/release
    tags:
      - "*.*.*"

jobs:
  build:
    uses: ./.github/workflows/flatpak-build.yml
    with:
      upload: true
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: download
        name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: bongocat-x86_64
          path: artifacts
      - name: 'Display downloaded artifacts'
        run: ls -R ${{steps.download.outputs.download-path}}
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ${{steps.download.outputs.download-path}}/artifacts/bongocat.flatpak