name: '[CI]: Snap build'
on:
  workflow_call:

jobs:
  appimage:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Copy snapcraft.yaml to the root dir"
        run: cp snap/local/snapcraft.yaml .
      - name: "Build package with snapcraft"
        uses: snapcore/action-build@v1
      - uses: actions/upload-artifact@v3
        with:
          name: bongocat-snap-x86_64
          path: bongocat_*.snap
